CREATE TABLE [ARCHIVE_DEBITEUR] (
  [Déb_Code_Client] VARCHAR (5),
  [Déb_Code] VARCHAR (10) CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Déb_Qualité] VARCHAR (3),
  [Déb_Nom] VARCHAR (82),
  [Déb_Code_Enc] VARCHAR (3),
  [Déb_Situation] VARCHAR (2),
  [Déb_niv_relance] SHORT,
  [Déb_Npai] BIT,
  [Déb_Date_proch_rel] DATETIME,
  [Déb_Date_der_rel] DATETIME,
  [Déb_Date_Cré] DATETIME,
  [Déb_Typ_Cré] VARCHAR (150),
  [Déb_MonnaieEnCours] LONG,
  [Déb_Frais_m1] CURRENCY,
  [Déb_Frais_m2] CURRENCY,
  [Déb_Mont_Prin_m1] CURRENCY,
  [Déb_Mont_Prin_m2] CURRENCY,
  [Déb_Mont_Prin_mo] LONG,
  [Déb_Date_Représentation] DATETIME,
  [Déb_Repré_Type] VARCHAR (5),
  [Déb_Mont_Origine_Cli] CURRENCY,
  [Déb_Mont_Récup_Cli] CURRENCY,
  [Déb_Réf1_Client] VARCHAR (30),
  [Déb_Réf2_Client] VARCHAR (30),
  [Déb_Nom_Banque] VARCHAR (50),
  [Déb_Date_Chèque] DATETIME,
  [Déb_Num_Chèque] VARCHAR (30),
  [Déb_RIB_Banque] VARCHAR (10),
  [Déb_RIB_Guichet] VARCHAR (10),
  [Déb_RIB_Compte] VARCHAR (11),
  [Déb_RIB_Clé] VARCHAR (2),
  [Déb_RIB_Dom] VARCHAR (50),
  [Déb_Observation] LONGTEXT,
  [Déb_Phoning] LONGTEXT,
  [Déb_Clé_Impayé] LONG,
  [Déb_Lot_IMPD_Id] LONG,
  [Déb_Lot_EID_Id] LONG
)
